// Mocks generated by Mockito 5.4.4 from annotations
// in meows_pedia/test/cat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:meows_pedia/data/models/cat_model.dart' as _i4;
import 'package:meows_pedia/domain/datasources/cat_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRemoteDataSource extends _i1.Mock
    implements _i2.CatRemoteDataSource {
  MockCatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CatModel>> fetchCats({
    int? limit = 10,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCats,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue: _i3.Future<List<_i4.CatModel>>.value(<_i4.CatModel>[]),
      ) as _i3.Future<List<_i4.CatModel>>);

  @override
  _i3.Future<String?> fetchCatImage(String? referenceImageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCatImage,
          [referenceImageId],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
